sudo: false
jdk: oraclejdk7
language: android
android:
  components:
  - extra-android-m2repository
script: mvn clean package -Dandroid.device=test -B -U
after_success: mvn deploy -e
env:
  global:
    secure: PiAItmTUSiZa+zVyAHfWpsRsz6kXrKUqkJosb3kdOS7KzPYNSvNlrq7esJyi/qL6+KymXS9EsRmUYMPgBMu7bbUcOYuk9X5gn3/MJjoxz1QVipvSri2tl21c69hWkZ6q80Z3YnHzyXhjzA4Pv7zfGajt2KbOSKI9FI2Z2N6CucnUcIK/3ML9mAXdbzzv5+qON16nNjSZxZq4EMBsyj8iUGcOGnZuVtP/OECAsbspp0yxWNs6Sh4v/IcJGUm4JB6FwoG/xq51a/TPtRtynq0UMufMsDZsZ/aboTPrF8AzX3QVd9X3r6ZURgbY4otav4glEPYcPUtHG86c57wa8rewvI1dZ9Trw/SWOBUyag/Z6bG8SKKnWbFdkU7IZiUewC3ERH5HO4oM73D8JrT3HpiV8vufh+Bv0zTkZDVP6ooVzkHt+ZNe0kUoIPgbeA0hlDWmSXLRM8JlgL+nE+gW6hLqO1llPfML+xQMyl4mCWv2j1pScVwttIPN6XhBgvxhKO0HSoH5Zk08IqisSbV5E1/XdtLHIwTq8wzH4y64fNIhKwD6HzHiq51VEI27TZIok7xBN3KnsTxdFeWMjiwx7Bd/J9TAjqXlsZh22DdhWAofaHRniMTEU2FlKe6GoK4MJJ75U38SdQZ19wvA435gcf0DQasKmzRvvZgRdOwpXzgMMU0=
